services:
    #TokenAuth Handler
    token_auth.handler:
        class: VIS\Bundle\ApiBundle\Component\Http\Storage\DB\TokenAuthHandler
        arguments: ["@doctrine.orm.entity_manager", 'VIS\Bundle\CoreBundle\Entity\UserToken']

    #TokenManager
    vis_api.security.token_auth.token_manager:
        class: VIS\Bundle\ApiBundle\Security\Authentication\Manager\TokenAuthManager
        arguments: ["@token_auth.handler", "@doctrine.orm.entity_manager", '%token_auth.expired_time%']

    #TokenAuth Provider
    vis_api.security.token_auth.provider:
        class: VIS\Bundle\ApiBundle\Security\Authentication\Manager\TokenAuthManager
        arguments: ['%kernel.cache_dir%/security/nonces', "@vis_api.security.token_auth.token_manager"]

    #TokenAuth Listener
    vis_api.security.token_auth.listener:
        class: VIS\Bundle\ApiBundle\Security\Authentication\Manager\TokenAuthManager
        arguments: ["@security.token_storage", "@security.authentication.manager"]